### ISSUE TITLE
Discrepant parameter names in GAMBLR.results::get_ssm_by_sample and GAMBLR.data::get_ssm_by_sample

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR.results#20]
Discrepant parameter names for `these_sample_ids` in the two functions reported above. In `GAMBLR.results::get_ssm_by_sample` we have `this_sample_id` and the corresponding parameter in `GAMBLR.data::get_ssm_by_sample` is `these_sample_ids`. I think the reason for this is that in GAMBLR.data there is no function called `get_ssm_by_sample` per se, rather, this package creates an alias for `get_ssm_by_samples` (the plural version) and this function calls the `these_sample_ids` parameter.  I think the parameter in GAMBLR.results should have its parameter renamed to match what is in GAMBLR.data, hence the issue created on this repo.

**Comment by vladimirsouza** [comment]
For greater consistency, I think `get_ssm_by_sample` should use `this_sample_id` (both singular) and `get_ssm_by_samples` to use `these_sample_ids` (both plural). 

I made a [PR](https://github.com/morinlab/GAMBLR.data/pull/45) in GAMBLR.data to ensure this consistency.
